#!/usr/bin/env python3

import datetime
import math
from decimal import *


today = datetime.datetime.today()

def main ():
    user_input = input( "Day that the subscription started, format should be YYYY-MM-DD : ")
    day = user_input [-2:]
    result = ""
    if int(day) < 15:
        result =  "{}-01".format(user_input[:-3])
        result = datetime.datetime.strptime(result, '%Y-%m-%d')
        print(result)
        diff=today-result
        print("Amount of days Premuim has been accessiable",diff)
        print("Amount of days for refund:",365-diff.days)
        price = 2.16438356
        payback = 790 - (diff.days * price)
        print("Customer's refund is:{:.2f}SEK".format(payback))
    else:
        user_input = datetime.datetime.strptime(user_input, '%Y-%m-%d')
        diff = today - user_input
        print("Amount of days Premuim has been accessiable", diff)
        print("Amount of days for refund:",365-diff.days)
        price = 2.16438356
        payback = 790 - (diff.days * price)
        print("Customer's refund is:{:.2f}SEK".format(payback))

        #Day price if sub was started with black friday discount: 1.08516485

if __name__ == '__main__':
    main()

    main()





